### PR TITLE
Profile popup

### PR DESCRIPTION
**Pull request by jinudean**
please review and give me a feed back

### CODE REVIEW

**Comment by zxkevinxz** [comment]
I think there was some confusion here. The profile fragment is what is accessed from the side navigation menu after you pick a profile an enter the app. Then it should show the profile info there and have the fields be editable with a save button.

**Comment by jinudean** [comment]
> I think there was some confusion here. The profile fragment is what is accessed from the side navigation menu after you pick a profile an enter the app. Then it should show the profile info there and have the fields be editable with a save button.

I got it but i think I don't have time to do before submit this week. somebody working on to start enter app after click profile?

**Comment by zxkevinxz** [comment]
The first page is done already. It picks whatever profile you select and a current profile variable is passed into the next activity. Whenever you have time, I can walk you through it on a video call.

**Review by zxkevinxz — APPROVED** [review]
Great work!

**Pull request merged**
